#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc config top_padding 0
bspc config click_to_focus		any

bspc config focus_follows_pointer false

bspc config pointer_follows_monitor	true

bspc config focused_border_color "#000000" 
bspc config normal_border_color "#2f343f"

bspc config ignore_ewmh_focus true

#bspc monitor HDMI-1 -d 1:dev-tmux 2:dev-browser
#bspc monitor eDP-1 -d 3:browse-anything 4:discord 5:slack

bspc monitor eDP-1 -d 1:dev-tmux 2:dev-browser 3:slack

bspc config border_width         4
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Brave desktop='^2'
bspc rule -a lightcord desktop='^4'
bspc rule -a Slack desktop='^5'
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off


autorandr --change

$HOME/.config/polybar/launch.sh --forest
nitrogen --set-auto /home/regmicmahesh/Pictures/wallpaper.jpg --head=0 && nitrogen --set-auto /home/regmicmahesh/Pictures/wallpaper.jpg --head=1
setxkbmap -layout us -option caps:escape


dunst
